import { Component, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { ApiService } from '../core/api.service';

@Component({ standalone: true, imports: [DatePipe, MatCardModule, MatButtonModule, RouterLink], template: `
<section class="heading"><div><h1>Tableau de bord</h1><p>Vue d’ensemble des stocks et équipements.</p></div><a mat-flat-button routerLink="/mouvements">Nouveau mouvement</a></section>
@if (data(); as d) { <div class="cards"><mat-card><small>Produits</small><strong>{{d.products}}</strong></mat-card><mat-card><small>Stock total</small><strong>{{d.stock_quantity}}</strong></mat-card><mat-card class="alert"><small>Stock faible</small><strong>{{d.low_stock}}</strong></mat-card><mat-card><small>Équipements</small><strong>{{d.assets}}</strong></mat-card><mat-card class="alert"><small>Lots expirés</small><strong>{{d.expired_lots}}</strong></mat-card><mat-card class="alert"><small>Hors service</small><strong>{{d.assets_out_of_service}}</strong></mat-card></div>
<div class="grid"><mat-card><h2>Derniers mouvements</h2><table><thead><tr><th>Référence</th><th>Produit</th><th>Type</th><th>Date</th></tr></thead><tbody>@for(m of d.recent_movements;track m.id){<tr><td>{{m.reference}}</td><td>{{m.product?.name}}</td><td>{{m.type}}</td><td>{{m.performed_at | date:'dd/MM/yyyy HH:mm'}}</td></tr>}</tbody></table></mat-card><mat-card><h2>Alertes actives</h2><p>{{d.low_stock}} produit(s) au seuil ou sous le seuil minimum.</p><p>{{d.expiring_lots}} lot(s) expirent dans les 30 jours.</p><p>{{d.assets_in_maintenance}} équipement(s) en maintenance.</p></mat-card></div> } @else { <p>Chargement…</p> }`, styles: `.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.heading h1{margin:0;font-size:28px}.heading p{color:#687278;margin:5px 0}.heading a{background:#123a4a;color:#fff}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.cards mat-card{padding:16px;border-left:4px solid #2a7085}.cards .alert{border-color:#c99123}.cards small{display:block;color:#687278}.cards strong{display:block;font-size:30px;margin-top:8px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px;margin-top:18px}.grid mat-card{padding:18px}h2{font-size:17px;margin-top:0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 5px;border-bottom:1px solid #e6e8e9;font-size:13px}@media(max-width:1000px){.cards{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:560px){.cards{grid-template-columns:repeat(2,1fr)}.heading{align-items:start;gap:10px;flex-direction:column}}` })
export class DashboardComponent { private api = inject(ApiService); readonly data = signal<any>(null); constructor(){ this.api.get<any>('dashboard').subscribe(d => this.data.set(d)); } }
