import { Component, inject, signal } from '@angular/core';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { ApiService } from '../core/api.service';

@Component({ standalone: true, imports: [FormsModule, ReactiveFormsModule, MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatSlideToggleModule], template: `
<section class="heading"><div><h1>Produits</h1><p>Fournitures, consommables et denrées.</p></div><button mat-stroked-button (click)="formOpen.set(!formOpen())">{{formOpen() ? 'Fermer' : 'Ajouter un produit'}}</button></section>
@if(formOpen()){<mat-card class="form-card"><form [formGroup]="form" (ngSubmit)="save()"><mat-form-field><mat-label>Référence</mat-label><input matInput formControlName="reference"></mat-form-field><mat-form-field><mat-label>Désignation</mat-label><input matInput formControlName="name"></mat-form-field><mat-form-field><mat-label>Unité</mat-label><mat-select formControlName="unit_id">@for(x of units();track x.id){<mat-option [value]="x.id">{{x.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Catégorie</mat-label><mat-select formControlName="category_id"><mat-option [value]="null">Aucune</mat-option>@for(x of categories();track x.id){<mat-option [value]="x.id">{{x.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Seuil minimum</mat-label><input matInput type="number" formControlName="minimum_stock"></mat-form-field><mat-form-field><mat-label>Prix d’achat (MAD)</mat-label><input matInput type="number" formControlName="purchase_price"></mat-form-field><mat-slide-toggle formControlName="track_lots">Gestion par lots</mat-slide-toggle><button mat-flat-button [disabled]="form.invalid">Enregistrer</button></form></mat-card>}
<mat-card class="list"><div class="tools"><mat-form-field><mat-label>Rechercher</mat-label><input matInput [(ngModel)]="search" (keyup.enter)="load()"></mat-form-field><button mat-button (click)="load()">Rechercher</button></div><table><thead><tr><th>Référence</th><th>Désignation</th><th>Catégorie</th><th>Stock</th><th>Seuil</th></tr></thead><tbody>@for(p of products();track p.id){<tr><td>{{p.reference}}</td><td>{{p.name}}</td><td>{{p.category?.name || '—'}}</td><td>{{p.stock_quantity || 0}} {{p.unit?.symbol}}</td><td>{{p.minimum_stock}}</td></tr>}@empty{<tr><td colspan="5">Aucun produit.</td></tr>}</tbody></table></mat-card>`, styles: `.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}h1{margin:0;font-size:28px}p{color:#687278;margin:5px 0}.form-card,.list{padding:18px;margin-bottom:18px}form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;align-items:center}.form-card button{background:#123a4a;color:white}.tools{display:flex;align-items:center;gap:8px}.tools mat-form-field{width:280px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 8px;border-bottom:1px solid #e6e8e9}@media(max-width:700px){form{grid-template-columns:1fr}.tools mat-form-field{width:100%}}` })
export class ProductsComponent {
  private api = inject(ApiService); private fb = inject(FormBuilder); readonly products = signal<any[]>([]); readonly categories = signal<any[]>([]); readonly units = signal<any[]>([]); readonly formOpen = signal(false); search = '';
  readonly form = this.fb.group({reference:['',Validators.required],name:['',Validators.required],unit_id:[null,Validators.required],category_id:[null],minimum_stock:[0,Validators.min(0)],purchase_price:[null],track_lots:[false],active:[true]});
  constructor(){this.load();this.api.get<any>('settings/categories').subscribe(x=>this.categories.set(x.data));this.api.get<any>('settings/units').subscribe(x=>this.units.set(x.data));}
  load(){this.api.get<any>('products',{search:this.search}).subscribe(x=>this.products.set(x.data));} save(){if(this.form.invalid)return;this.api.post('products',this.form.getRawValue()).subscribe(()=>{this.form.reset({minimum_stock:0,track_lots:false,active:true});this.formOpen.set(false);this.load();});}
}
