import { Component, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { ApiService } from '../core/api.service';
@Component({standalone:true,imports:[DatePipe,ReactiveFormsModule,MatButtonModule,MatCardModule,MatFormFieldModule,MatInputModule,MatSelectModule],template:`
<section class="heading"><h1>Mouvements de stock</h1><p>Chaque opération est définitive et tracée.</p></section><mat-card class="form-card"><h2>Nouveau mouvement</h2><form [formGroup]="form" (ngSubmit)="save()"><mat-form-field><mat-label>Type</mat-label><mat-select formControlName="type">@for(t of types;track t){<mat-option [value]="t">{{labels[t]}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Produit</mat-label><mat-select formControlName="product_id">@for(p of products();track p.id){<mat-option [value]="p.id">{{p.reference}} — {{p.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Quantité</mat-label><input matInput type="number" formControlName="quantity"></mat-form-field><mat-form-field><mat-label>Source</mat-label><mat-select formControlName="source_location_id"><mat-option [value]="null">—</mat-option>@for(l of locations();track l.id){<mat-option [value]="l.id">{{l.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Destination</mat-label><mat-select formControlName="destination_location_id"><mat-option [value]="null">—</mat-option>@for(l of locations();track l.id){<mat-option [value]="l.id">{{l.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>Motif</mat-label><input matInput formControlName="reason"></mat-form-field><button mat-flat-button [disabled]="form.invalid">Valider le mouvement</button></form></mat-card><mat-card class="list"><table><thead><tr><th>Référence</th><th>Type</th><th>Produit</th><th>Quantité</th><th>Date</th></tr></thead><tbody>@for(m of movements();track m.id){<tr><td>{{m.reference}}</td><td>{{labels[m.type]}}</td><td>{{m.product?.name}}</td><td>{{m.quantity}}</td><td>{{m.performed_at | date:'dd/MM/yyyy HH:mm'}}</td></tr>}</tbody></table></mat-card>`,styles:`.heading{margin-bottom:18px}h1{margin:0;font-size:28px}p{color:#687278}.form-card,.list{padding:18px;margin-bottom:18px}h2{margin-top:0;font-size:18px}form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.form-card button{background:#123a4a;color:#fff}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 8px;border-bottom:1px solid #e6e8e9}@media(max-width:700px){form{grid-template-columns:1fr}}`})
export class StockComponent {private api=inject(ApiService);private fb=inject(FormBuilder);readonly products=signal<any[]>([]);readonly locations=signal<any[]>([]);readonly movements=signal<any[]>([]);readonly types=['entry','exit','return','transfer','adjustment','loss','disposal'];readonly labels:any={entry:'Entrée',exit:'Sortie',return:'Retour',transfer:'Transfert',adjustment:'Ajustement',loss:'Perte',disposal:'Mise au rebut'};readonly form=this.fb.group({type:['entry',Validators.required],product_id:[null,Validators.required],quantity:[null,[Validators.required,Validators.min(0.001)]],source_location_id:[null],destination_location_id:[null],reason:['']});constructor(){this.api.get<any>('products',{per_page:100}).subscribe(x=>this.products.set(x.data));this.api.get<any>('settings/locations').subscribe(x=>this.locations.set(x.data));this.load();}load(){this.api.get<any>('stock/movements').subscribe(x=>this.movements.set(x.data));}save(){if(this.form.invalid)return;this.api.post('stock/movements',this.form.getRawValue()).subscribe({next:()=>{this.form.patchValue({quantity:null,reason:''});this.load();}});}}
